//FUNCTION
//é um objeto do tipo função

function name(param){ }; //definindo a função

function name(param){
name(function ()
{console.log("param")
});
} 
//invocando ela e passando como parâmetro

function name(params) {
    return function() {
    
    }
}
//retornando ela

//exemplo prático
function sum(a, b){
    a:1
    b:5
    return 1+5;
}; 
console.log(sum);

//outro
function me(zgy){
    return 'call me '+$
}
console.log(me)

//outro

function character(name, show, category){
    name: 'steve';
    show: 'mommy';
    category: 'movie'
    
    return name+','+show+','+category
}
console.log(character)
